function(run_pq output_var error_var result_var)
    execute_process(
        COMMAND "${PQ_EXECUTABLE}" ${ARGN}
        RESULT_VARIABLE result
        OUTPUT_VARIABLE output
        ERROR_VARIABLE error
    )
    set(${output_var} "${output}" PARENT_SCOPE)
    set(${error_var} "${error}" PARENT_SCOPE)
    set(${result_var} "${result}" PARENT_SCOPE)
endfunction()

run_pq(output error result --help)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "PQ --help returned ${result}: ${error}")
endif()
if(NOT output MATCHES "^Usage: PQ <input_file>")
    message(FATAL_ERROR "PQ --help did not print usage: ${output}")
endif()
if(NOT error STREQUAL "")
    message(FATAL_ERROR "PQ --help wrote to stderr: ${error}")
endif()

run_pq(output error result --version)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "PQ --version returned ${result}: ${error}")
endif()
if(NOT output STREQUAL "PQ ${EXPECTED_VERSION}\n")
    message(
        FATAL_ERROR
        "PQ --version printed '${output}', expected 'PQ ${EXPECTED_VERSION}'"
    )
endif()
if(NOT error STREQUAL "")
    message(FATAL_ERROR "PQ --version wrote to stderr: ${error}")
endif()

run_pq(output error result --unknown)
if(result EQUAL 0)
    message(FATAL_ERROR "PQ --unknown returned success")
endif()
if(NOT output STREQUAL "")
    message(FATAL_ERROR "PQ --unknown wrote to stdout: ${output}")
endif()
if(NOT error MATCHES "Unknown option: --unknown")
    message(FATAL_ERROR "PQ --unknown did not report the option: ${error}")
endif()

run_pq(output error result)
if(result EQUAL 0)
    message(FATAL_ERROR "PQ without an input returned success")
endif()
if(NOT output STREQUAL "")
    message(FATAL_ERROR "PQ without an input wrote to stdout: ${output}")
endif()
if(NOT error MATCHES "No input file specified")
    message(FATAL_ERROR "PQ without an input did not report the error: ${error}")
endif()

run_pq(output error result missing-input.in)
if(result EQUAL 0)
    message(FATAL_ERROR "PQ with a missing input returned success")
endif()
if(NOT output STREQUAL "")
    message(FATAL_ERROR "PQ with a missing input wrote to stdout: ${output}")
endif()
if(NOT error MATCHES "File not found")
    message(FATAL_ERROR "PQ with a missing input did not report the error: ${error}")
endif()

run_pq(output error result missing-input.in extra)
if(result EQUAL 0)
    message(FATAL_ERROR "PQ with an extra argument returned success")
endif()
if(NOT output STREQUAL "")
    message(FATAL_ERROR "PQ with an extra argument wrote to stdout: ${output}")
endif()
if(NOT error MATCHES "Unexpected argument: extra")
    message(FATAL_ERROR "PQ did not report the extra argument: ${error}")
endif()
