#!/usr/bin/perl
#
#  turbomole_hf+dft
#
#  Interface between PQ and Turbomole
#  initializes QM run: define
#  runs QM calculation: dscf, grad, moloch2
#  etracts data - energy, gradient, pointcharges
#
# + check if inital mo guess can be reused via $changed
#   if YES ($changed == 1)
#     + remove old turbomole files
#     + make tm_define.in from tm_define.template
#     + run define with tm_define.in 
#     + check the pointcharge scheme ($pointcharge_scheme [0 mulliken, 1 loewdin])
# + insert point-charges from $pointcharges_file to control file
# + run dscf
# + remove point_charges
#   if pointcharges have been used
#     + compute energy without pointcharge contribution
# + extract energy and write it to $qm_forces
# + run grad
# + extract gradients and write them to $qm_forces
# + run moloch2
# + extract charges and write them to $qm_charges
# + exit script
#


use strict;

# subroutines
use subs qw(insert_pointcharges);
use subs qw(remove_pointcharges);


# script's name
my $progname = $0;
$progname =~ s{^.*/}{};


# input data from the PQ programm
my $charge             = $ARGV[0];             # charge of the qm region
my $changed            = $ARGV[1];             # flag if define has to be run
my $guess_mo           = $ARGV[2];             # flag if a dft step is performed as a guess
my $pointcharge_scheme = $ARGV[3];             # pointcharge scheme
my $nprocessors        = $ARGV[4];             # number of processors
my $pointcharges_file  = $ARGV[5];             # name of the pointcharges_file


# various variables
my $line;                                      # helper variable - gradient
my $flag = undef;                              # helper variable - moloch
my $start_flag         = "";                   # helper variable - moloch
my $stop_flag          = "";                   # helper variable - moloch
my $energy;                                    # QM energy
my $control_contents   = "";                   # helper variable - control file modifications
my $tm_out             = "";                   # output of define, dscf, and grad
my $converged_string   = 'convergence criteria satisfied after\s*\d+' .
  '\s+iterations';		                         # energy search string
my $n_pointcharges;                            # number of pointcharges variable   


# files and commands
my $qm_coords          = "coord";              # coordinate file
# my $mm_pointcharges    = "mm_pointcharges";    # coordinates of pointcharges
my $dscf_exe           = "dscf";                # tm modul for scf calculation
my $grad_exe           = "grad";	       # tm modul for gradient calculation
my $define_template    = "tm_define.template"; # must exist before you start!
my $control_file       = "control";            # tm control file
my $energy_file        = "energy";             # tm output energy
my $gradient_file      = "gradient";           # tm output gradients
my $moloch_out         = "moloch.out";         # tm output population analysis   

my $qm_forces          = "qm_forces";          # result file: energy plus forces of all qm atoms
my $qm_charges         = "qm_charges";         # result file: partial charges of all qm atoms

my $dscf_nopc_out      = "dscf_nopc.out";      # dscf file - no pointcharges                                 
my $out_file           = "tm.out";	           # summary file
my $out_file_prev      = "tm.out.prev";        # summary file - previous step
my $qm_coords_prev     = "coord.prev";         # summary file - coordinates previous step
# my $mm_pointcharges_prev =  "mm_pointcharges.prev";

my $energy_nopc;

my $pointcharges = 0;      # change later to read it as command line argument: 0 - no pointcharges, 1 - pointcharges

if ($changed == 1)
  {
    unlink "control";
    unlink "basis";
    unlink "mos";
    unlink "alpha";
    unlink "beta";
    unlink "tmp.input";

# create tm_define.in from tm_define.template
# and insert QM charge
    open (TM_DEFINE_TEMPLATE, "< tm_define.template") or
         die "\n\n\t (-) $progname: Error opening file 'tm_define.template'\n";

    open (TM_DEFINE_IN, "> tm_define.in") or
         die "\n\n\t (-) $progname: Error opening file 'tm_define.in'\n";

    while (<TM_DEFINE_TEMPLATE>)
    {
       s{__CHARGE__}{$charge};
       print TM_DEFINE_IN;
    }

   close (TM_DEFINE_TEMPLATE);
   close (TM_DEFINE_IN);

# execute the define
   $tm_out = `define < tm_define.in 2>&1 | tee $out_file`;

# replace mulliken by loewdin if requested
   if ($pointcharge_scheme == 1)
     {

      open (CONTROL, "< $control_file") or
         die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

       while (<CONTROL>)
         {
            s{mulliken}{loewdin};
            $control_contents .= $_;
         }
      close (CONTORL);

      open (CONTROL, "> $control_file") or
            die "\n\n\t (-) $progname: Error opening file '$control_file'\n";
      print CONTROL $control_contents;
      close (CONTORL);
     }
  }

if ($pointcharges == 1)
{
  # insert pointcharges in the control file
    insert_pointcharges;
}
  
# execute dscf
$tm_out = `$dscf_exe $nprocessors 2>&1 | tee $out_file`;	
exit 1 if ($tm_out !~ /$converged_string/);



if ($pointcharges == 1)
{
  remove_pointcharges;

  # compute energy without pointcharge contribution
  # save files control and mos for grad calc
  `cp control control.bak`;
  `cp mos mos.bak`;

  $control_contents = "";

  open (CONTROL, "< $control_file") or
    die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

  while (<CONTROL>) 
  {
  if (/^\s*\$scfiterlimit/)
  { 
    $control_contents .= "\$scfiterlimit      1\n"
  }
  else
  {
    $control_contents .= $_;
  }
  }
  close (CONTORL);

  open (CONTROL, "> $control_file") or
    die "\n\n\t (-) $progname: Error opening file '$control_file'\n";
  print CONTROL $control_contents;
  close (CONTORL);

  # execute dscf
  `$dscf_exe $nprocessors 2>&1 | tee $dscf_nopc_out`;
}

# read in energy from dscf output, if pointcharges are used read from dscf_nopc.out
my $energy_file_to_open = ($pointcharges == 1) ? $dscf_nopc_out : $out_file;
open (ENERGY, "< $energy_file_to_open") or
  die "\n\n\t (-)  Error opening file '$energy_file_to_open'\n";

while (<ENERGY>) 
  {
      
    if (/^\s+1\s+-\d+.\d+\s+-\d+.\d+\s+\d+.\d+\s+\d+.\d+D\+\d+\s+\d+.\d+D/)
    {
      $line = $_;
      $energy = (split ' ', $line)[1];
    }
  }
close (ENERGY);

if ($pointcharges == 1)
{
  `cp control.bak control`;
  `cp mos.bak mos`;
  unlink "dscf_problem";
}

unlink $gradient_file;   
# execute the grad
$tm_out = `grad $nprocessors 2>&1 | tee -a $out_file`;	
exit 1 if ($tm_out !~ /grad ended normally/);

open (FORCES, "> $qm_forces") or
  die "\n\n\t (-) $progname: Error opening file '$qm_forces'\n";

# write QM energy to qm_forces
print FORCES "$energy\n";

# extract gradient
open (GRADIENT, "< $gradient_file") or
  die "\n\n\t (-) $progname: Error opening file '$gradient_file'\n";

while (<GRADIENT>) {
  next if /^\s*\$grad/;
  next if /^\s*cycle =/;
  last if /^\s*\$end/;

  # change exponential D into exponential E
  y/D/E/;

  my @gradient = split;

 # write  gradient to qm_forces
  if ($#gradient == 2) {
    printf FORCES ("%20.14G  %20.14G  %20.14G\n",
		   $gradient[0], $gradient[1], $gradient[2]);
  }
}

close (FORCES);
close (GRADIENT);

# run moloch2 to calculate charges of QM atoms

# RHF-calculations: moloch.out is in the working directory
# UHF-calculations: moloch.out is in working/moloch_n_dir/
# in case of UHF - copy moloch.out into the working directory

unlink $moloch_out;

$tm_out =`moloch2  2>&1 | tee -a $out_file`;
if (-f "moloch_n_dir/moloch.out") {
        `cp -f moloch_n_dir/moloch.out moloch.out`;
}

# extract qm partial charges
# mulliken
if ($pointcharge_scheme == 0)
{
  $start_flag = "atomic brutto population";
  $stop_flag  = "atomic netto population";
}
# loewdin
elsif ($pointcharge_scheme == 1)
{
  $start_flag = "loewdin population analysis";
  $stop_flag  = "elapsed time for loewdin population analysis";
}

open(MOLOCH , "< $moloch_out") or
   die "\n\n\t (-) $progname: Error opening file '$moloch_out'\n";
     
open(CHARGE, "> $qm_charges") or 
   die "\n\n\t (-) $progname: Error opening file '$qm_charges'\n";

while (<MOLOCH>) 
  {
    last if ($_ =~ m/$stop_flag/);
    $flag = 1 if ($_ =~ m/$start_flag/);
    if ($flag && m/charge/) 
      {
         my $line = $_;
         $line =~ s/\s+\S+\s+\S+\s+(\S+)\s+\S+\s\S+\s\S\s+\S+\s+\S+\s\S\s+(\S+)/$1 $2/;
         my @item = split(/\s+/, $line);
         printf CHARGE ("%s  %11.4f\n", @item);
      }
  }
close(MOLOCH);
close(CHARGE);

exit 0;



#### SUBROUTINES ###

# append point-charges keyword and values before the $end of the $control_file
sub insert_pointcharges {
  my $control_contents = "";

  open (CONTROL, "< $control_file") or
    die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

  while (<CONTROL>) {
    last if /^\s*\$end/;

    $control_contents .= $_;
  }
  close (CONTROL);

  open (CONTROL, "> $control_file") or
    die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

  open (PNT_CHARGE, "< $pointcharges_file") or
    die "\n\n\t (-) $progname: Error opening file '$pointcharges_file'\n";

  print CONTROL $control_contents;
  print CONTROL "\$point_charges\n";

  while (<PNT_CHARGE>) {
    my @line = split;
    printf CONTROL ("%14.8f %14.8f %14.8f %10.6f\n",
                    $line[0], $line[1],$line[2], $line[3]);
  }
  close (PNT_CHARGE);

  print CONTROL "\$end\n";

  close (CONTROL);
}

# delete pointcharges in the $control_file
sub remove_pointcharges {
  my $contents = undef;
  my $flag = undef;
  open (CONTROL, "< $control_file") or
        die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

  while(<CONTROL>) {
    $flag = 1 if(m/^\$point_charges/);
    if ($flag) {
      $flag = undef if ($_ =~ m/^\$/ && $_ !~ m/^\$point_charges/);
    }
    unless ($flag) {
      $contents .= $_;
    }
  }
  close (CONTROL);

  open (CONTROL, "> $control_file") or
      die "\n\n\t (-) $progname: Error opening file '$control_file'\n";
  print CONTROL $contents;
  close (CONTROL);
}

