#!/usr/bin/perl
#
#  turbomole_hf+dft
#
#  Interface between PQ and Turbomole
#  initializes QM run: define
#  runs QM calculation: dscf, grad
#  extracts data - energy, gradient, pointcharges
#
# + check if inital mo guess can be reused via $run_define
#   if YES ($run_define == 1)
#     + remove old turbomole files
#     + make tm_define.in from tm_define.template
#     + run define with tm_define.in
# + insert pointcharges from $pointcharges_file to control file
# + run dscf
# + remove pointcharges from control file
#   if pointcharges have been used
#     + compute energy without pointcharge contribution
# + run grad
# + extract energy and write it to $qm_forces
# + extract gradients and write them to $qm_forces
# + extract charges and write them to $qm_charges
# + exit script
#


use strict;

# subroutines
use subs qw(insert_pointcharges);
use subs qw(remove_pointcharges);


# script's name
my $progname = $0;
$progname =~ s{^.*/}{};

# input data from the PQ program
my $charge             = $ARGV[0];             # charge of the qm region
my $run_define         = $ARGV[1];             # flag if define has to be run
my $pointcharges       = $ARGV[2];             # flag if point charges are used
my $tm_template_file   = $ARGV[3];             # tm template file that generates tm_define.in
my $pointcharges_file  = $ARGV[4];             # name of the pointcharges_file

# various variables
my $line;                                      # helper variable
my $flag = undef;                              # helper variable
my $start_flag         = "";                   # helper variable
my $stop_flag          = "";                   # helper variable
my $energy;                                    # QM energy
my $control_contents   = "";                   # helper variable - control file modifications
my $tm_out             = "";                   # output of define, dscf, and grad
my $converged_string   = 'convergence criteria satisfied after\s*\d+' .
  '\s+iterations';		                         # energy search string
my $n_pointcharges;                            # number of pointcharges variable   

# files and commands
my $qm_coords          = "coord";              # coordinate file
my $dscf_exe           = "dscf";               # tm modul for scf calculation
my $grad_exe           = "grad";	             # tm modul for gradient calculation
my $control_file       = "control";            # tm control file
my $energy_file        = "energy";             # tm output energy
my $gradient_file      = "gradient";           # tm output gradients

my $qm_forces          = "qm_forces";          # result file: energy plus forces of all qm atoms
my $qm_charges         = "qm_charges";         # result file: partial charges of all qm atoms

my $dscf_nopc_out      = "dscf_nopc.out";      # dscf file - no pointcharges                                 
my $out_file           = "tm.out";	           # summary file

if ($run_define == 1)
{
  unlink "control";
  unlink "basis";
  unlink "mos";
  unlink "alpha";
  unlink "beta";
  unlink "tmp.input";

# create tm_define.in from $tm_template_file
# and insert QM charge
  open (TM_DEFINE_TEMPLATE, "< $tm_template_file") or
        die "\n\n\t (-) $progname: Error opening file 'tm_define.template'\n";

  open (TM_DEFINE_IN, "> $tm_template_file") or
        die "\n\n\t (-) $progname: Error opening file 'tm_define.in'\n";

  while (<TM_DEFINE_TEMPLATE>)
  {
      s{__CHARGE__}{$charge};
      print TM_DEFINE_IN;
  }

  close (TM_DEFINE_TEMPLATE);
  close (TM_DEFINE_IN);

# execute the define
  $tm_out = `define < tm_define.in 2>&1 | tee $out_file`;
}

if ($pointcharges == 1)
{
    insert_pointcharges;
}

# execute dscf
$tm_out = `$dscf_exe 2>&1 | tee $out_file`;	
exit 1 if ($tm_out !~ /$converged_string/);

if ($pointcharges == 1)
{
  remove_pointcharges;

  # compute energy without pointcharge contribution
  # save files control and mos for grad calc
  `cp control control.bak`;
  `cp mos mos.bak 2>/dev/null`;
  `cp alpha alpha.bak 2>/dev/null`;
  `cp beta beta.bak 2>/dev/null`;

  $control_contents = "";


  open (CONTROL, "< $control_file") or
    die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

  while (<CONTROL>) 
  {
  if (/^\s*\$scfiterlimit/)
  { 
    $control_contents .= "\$scfiterlimit      1\n"
  }
  else
  {
    $control_contents .= $_;
  }
  }
  close (CONTORL);

  open (CONTROL, "> $control_file") or
    die "\n\n\t (-) $progname: Error opening file '$control_file'\n";
  print CONTROL $control_contents;
  close (CONTORL);

  # execute dscf
  `$dscf_exe 2>&1 | tee $dscf_nopc_out`;
}

if ($pointcharges == 1)
{
  # read in 1st SCF energy from dscf_nopc_out
  open (ENERGY, "< $dscf_nopc_out") or
    die "\n\n\t (-)  Error opening file '$dscf_nopc_out'\n";

  while (<ENERGY>) 
  {
      
    if (/^\s+1\s+-\d+.\d+\s+-\d+.\d+\s+\d+.\d+\s+\d+.\d+D\+\d+\s+\d+.\d+D/)
    {
      $line = $_;
      $energy = (split ' ', $line)[1];
    }
  }

  close (ENERGY);
}
else
{
# read in total energy from out_file
open (ENERGY, "< $out_file") or
  die "\n\n\t (-)  Error opening file '$out_file'\n";

 while (<ENERGY>)
 {
   last if /^\s+\:\s+kinetic/;

   y/D/E/;

   if (/^\s+\|\s+total/)
   {
      my @energy_line = split;

     $energy=$energy_line[4];   
   }
 }

close (ENERGY);
}

if ($pointcharges == 1)
{
  `cp control.bak control`;
  `cp mos.bak mos 2>/dev/null`;
  `cp alpha.bak alpha 2>/dev/null`;
  `cp beta.bak beta 2>/dev/null`;
}

unlink $gradient_file;   
# execute the grad
$tm_out = `grad 2>&1 | tee -a $out_file`;	
exit 1 if ($tm_out !~ /grad ended normally/);

open (FORCES, "> $qm_forces") or
  die "\n\n\t (-) $progname: Error opening file '$qm_forces'\n";

# write QM energy to qm_forces
print FORCES "$energy\n";

# extract gradient
open (GRADIENT, "< $gradient_file") or
  die "\n\n\t (-) $progname: Error opening file '$gradient_file'\n";

while (<GRADIENT>) {
  next if /^\s*\$grad/;
  next if /^\s*cycle =/;
  last if /^\s*\$end/;

  # change exponential D into exponential E
  y/D/E/;

  my @gradient = split;

  # Skip coordinate lines (4 entries: x, y, z, atom_type)
  next if ($#gradient == 3);

  # Process gradient lines (3 entries: force_x, force_y, force_z)
  if ($#gradient == 2) {
    printf FORCES ("%20.14G  %20.14G  %20.14G\n",
		   $gradient[0], $gradient[1], $gradient[2]);
  }
}

close (FORCES);
close (GRADIENT);

# initialize the correct flags
  # mulliken
$start_flag = "atom      charge";
$stop_flag  = "from total density versus population analysis";

my $charge_file_to_open = ($pointcharges == 1) ? $dscf_nopc_out : $out_file;
open(OUT, "< $charge_file_to_open") or
   die "\n\n\t (-) $progname: Error opening file '$charge_file_to_open'\n";
     
open(CHARGE, "> $qm_charges") or 
   die "\n\n\t (-) $progname: Error opening file '$qm_charges'\n";

while (<OUT>) 
  {
    last if ($_ =~ m/$stop_flag/);
    $flag = 1 if ($_ =~ m/$start_flag/);

    if ($flag && m/\s+\d+(\S+)\s+(\S+)/) 
      {
         my $line = $_;
  	     $line =~ s/\s+\d+(\S+)\s+(\S+)/$1 $2/;
         my @item = split(/\s+/, $line);
         printf CHARGE ("%s  %12.5f\n", @item);
      }
  }

close(OUT);
close(CHARGE);

exit 0;


#### SUBROUTINES ###

# append point-charges keyword and values before the $end of the $control_file
sub insert_pointcharges {
  my $control_contents = "";

  open (CONTROL, "< $control_file") or
    die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

  while (<CONTROL>) {
    last if /^\s*\$end/;

    $control_contents .= $_;
  }
  close (CONTROL);

  open (CONTROL, "> $control_file") or
    die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

  open (PNT_CHARGE, "< $pointcharges_file") or
    die "\n\n\t (-) $progname: Error opening file '$pointcharges_file'\n";

  print CONTROL $control_contents;
  print CONTROL "\$point_charges\n";

  while (<PNT_CHARGE>) {
    my @line = split;
    printf CONTROL ("%14.8f %14.8f %14.8f %10.6f\n",
                    $line[0], $line[1],$line[2], $line[3]);
  }
  close (PNT_CHARGE);

  print CONTROL "\$end\n";

  close (CONTROL);
}

# delete pointcharges in the $control_file
sub remove_pointcharges {
  my $contents = undef;
  my $flag = undef;
  open (CONTROL, "< $control_file") or
        die "\n\n\t (-) $progname: Error opening file '$control_file'\n";

  while(<CONTROL>) {
    $flag = 1 if(m/^\$point_charges/);
    if ($flag) {
      $flag = undef if ($_ =~ m/^\$/ && $_ !~ m/^\$point_charges/);
    }
    unless ($flag) {
      $contents .= $_;
    }
  }
  close (CONTROL);

  open (CONTROL, "> $control_file") or
      die "\n\n\t (-) $progname: Error opening file '$control_file'\n";
  print CONTROL $contents;
  close (CONTROL);
}

