add_library(pq_pch OBJECT dummy.cpp)
target_precompile_headers(pq_pch PRIVATE
    <format>
    <memory>
    <Eigen/Dense>
)
set_target_properties(pq_pch PROPERTIES
    POSITION_INDEPENDENT_CODE ON
)
target_link_libraries(pq_pch PUBLIC Eigen3::Eigen)

add_subdirectory(molsys)
add_subdirectory(config)
add_subdirectory(engine)
add_subdirectory(utilities)
add_subdirectory(output)
add_subdirectory(setup)
add_subdirectory(integrator)
add_subdirectory(potential)
add_subdirectory(timings)
add_subdirectory(thermostat)
add_subdirectory(manostat)
add_subdirectory(physicalData)
add_subdirectory(virial)
add_subdirectory(linearAlgebra)
add_subdirectory(resetKinetics)
add_subdirectory(constraints)
add_subdirectory(input)
add_subdirectory(connectivity)
add_subdirectory(forceField)
add_subdirectory(settings)
add_subdirectory(intraNonBonded)
add_subdirectory(waterModels/inter)
add_subdirectory(exceptions)
add_subdirectory(QM)
add_subdirectory(maxwellBoltzmann)
add_subdirectory(box)
add_subdirectory(kernels)
add_subdirectory(opt)
add_subdirectory(randomNumberGenerator)
add_subdirectory(hybridConfigurator)

if(BUILD_WITH_PYTHON_BINDINGS)
    add_definitions(-DWITH_WITH_PYTHON_BINDINGS)
    add_subdirectory(python)
endif()

if(BUILD_WITH_MPI)
    add_subdirectory(mpi)
endif()
