/*****************************************************************************
<GPL_HEADER>

    PQ
    Copyright (C) 2023-now  Jakob Gamper

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

<GPL_HEADER>
******************************************************************************/

#ifndef _INPUT_CONVERTER_HPP_
#define _INPUT_CONVERTER_HPP_

#include <charconv>
#include <concepts>
#include <optional>
#include <string>
#include <string_view>

#include "mstd/type_traits/enum_traits.hpp"

/**
 * @namespace input
 *
 * @brief namespace for reading input files
 *
 */
namespace input
{
    /**
     * @class Converter
     *
     * @brief pure, non-throwing conversion from a raw input-file token to a
     * value of type T. Specialized per T; the primary template is
     * intentionally left undefined so a missing specialization is a compile
     * error rather than a silent runtime bug.
     *
     * @tparam T
     */
    template <typename T>
    struct Converter;

    /**
     * @brief Converter specialization for double
     *
     */
    template <>
    struct Converter<double>
    {
        [[nodiscard]] static std::optional<double> tryParse(
            const std::string_view raw
        )
        {
            try
            {
                size_t            pos{};
                const std::string str(raw);
                const double      value = std::stod(str, &pos);

                if (pos != str.size())
                    return std::nullopt;

                return value;
            }
            catch (...)
            {
                return std::nullopt;
            }
        }
    };

    /**
     * @brief Converter specialization for bool
     *
     */
    template <>
    struct Converter<bool>
    {
        [[nodiscard]] static std::optional<bool> tryParse(
            const std::string_view raw
        )
        {
            if (raw == "TRUE" || raw == "ON")
                return true;
            if (raw == "FALSE" || raw == "OFF")
                return false;

            return std::nullopt;
        }
    };

    /**
     * @brief Converter specialization for plain integral types (size_t,
     * int, unsigned, ...), excluding bool
     *
     * @details covers keys with no natural enum/double/bool representation
     * (e.g. counts, indices) without requiring a per-key customParser for
     * the common case
     *
     * @tparam T
     */
    template <std::integral T>
    requires(!std::same_as<T, bool>)
    struct Converter<T>
    {
        [[nodiscard]] static std::optional<T> tryParse(
            const std::string_view raw
        )
        {
            T          value{};
            const auto result =
                std::from_chars(raw.data(), raw.data() + raw.size(), value);

            if (result.ec != std::errc{} ||
                result.ptr != raw.data() + raw.size())
                return std::nullopt;

            return value;
        }
    };

    /**
     * @brief Converter specialization for enums generated by MSTD_ENUM /
     * MSTD_ENUM_BITFLAG
     *
     * @details these enums already carry their own name<->value table via
     * mstd::enum_meta_t<T> -- no separately maintained map is needed here.
     * Per-key aliases or spellings the generated from_string can't express
     * go through InputKey's customParser instead.
     *
     * @tparam T
     */
    template <mstd::has_enum_meta T>
    struct Converter<T>
    {
        [[nodiscard]] static std::optional<T> tryParse(
            const std::string_view raw
        )
        {
            using Meta = mstd::enum_meta_t<T>;
            return Meta::from_string(raw);
        }

        [[nodiscard]] static std::string describeDomain()
        {
            using Meta = mstd::enum_meta_t<T>;

            std::string allowed;
            for (size_t i = 0; i < Meta::size; ++i)
            {
                if (i != 0)
                    allowed += ", ";
                allowed += std::string(Meta::names.at(i));
            }

            return allowed;
        }
    };

    /**
     * @brief describes the valid domain of T for error messages
     *
     * @details falls back to a generic placeholder for types without a
     * describeDomain() (i.e. everything except has_enum_meta<T>)
     *
     * @tparam T
     */
    template <typename T>
    [[nodiscard]] std::string describeDomain()
    {
        if constexpr (mstd::has_enum_meta<T>)
            return Converter<T>::describeDomain();
        else
            return "<value>";
    }
}   // namespace input

#endif   // _INPUT_CONVERTER_HPP_
