/*****************************************************************************
<GPL_HEADER>

    PQ
    Copyright (C) 2023-now  Jakob Gamper

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

<GPL_HEADER>
******************************************************************************/

#ifndef _INPUT_CONVERTER_HPP_
#define _INPUT_CONVERTER_HPP_

#include <concepts>
#include <cstdint>
#include <map>
#include <mstd/file.hpp>
#include <mstd/type_traits.hpp>
#include <optional>
#include <string>
#include <string_view>
#include <unordered_map>
#include <vector>

class TestInputFileReader;   // forward declaration

/**
 * @namespace input
 *
 * @brief namespace for reading input files
 *
 */
namespace input
{

    const std::map<std::string, std::string> boolKeywords = {
        {"on", "off"},
        {"true", "false"},
        {"yes", "no"}
    };

    /**
     * @brief Base class for all Converter specializations
     *
     * @tparam T
     */
    template <typename T>
    struct ConverterBase
    {
       private:
        std::string _key;
        std::string _raw;

       public:
        ConverterBase(std::string key, std::string raw);

        [[nodiscard]]
        static std::string describeDomain(const std::vector<T> &notAllowed);

       protected:
        [[nodiscard]]
        const std::string &_getKey() const
        {
            return _key;
        }

        [[nodiscard]]
        const std::string &_getRaw() const
        {
            return _raw;
        }
    };

    /**
     * @class Converter
     *
     * @brief pure, non-throwing conversion from a raw input-file token to a
     * value of type T. Specialized per T; the primary template is
     * intentionally left undefined so a missing specialization is a compile
     * error rather than a silent runtime bug.
     *
     * @tparam T
     */
    template <typename T>
    struct Converter : public ConverterBase<T>
    {
    };

    /**
     * @brief Converter specialization for double
     *
     */
    template <>
    struct Converter<double> : public ConverterBase<double>
    {
        using ConverterBase<double>::ConverterBase;

        [[nodiscard]]
        static std::optional<double> tryParse(std::string_view raw);
    };

    /**
     * @brief Converter specialization for bool
     *
     */
    template <>
    struct Converter<bool> : public ConverterBase<bool>
    {
        using ConverterBase<bool>::ConverterBase;

        [[nodiscard]]
        static std::optional<bool> tryParse(std::string_view raw);

        [[nodiscard]]
        static std::string describeDomain(const std::vector<bool> &notAllowed);
    };

    /**
     * @brief Converter specialization for plain integral types (size_t,
     * int, unsigned, ...), excluding bool
     *
     * @details covers keys with no natural enum/double/bool representation
     * (e.g. counts, indices) without requiring a per-key customParser for
     * the common case
     *
     * @tparam T
     */
    template <std::signed_integral T>
    requires(!std::same_as<T, bool>)
    struct Converter<T> : public ConverterBase<T>
    {
        using ConverterBase<T>::ConverterBase;

        [[nodiscard]]
        static std::optional<T> tryParse(std::string_view raw);
    };

    /**
     * @brief Converter specialization for plain integral types (size_t,
     * int, unsigned, ...), excluding bool
     *
     * @details covers keys with no natural enum/double/bool representation
     * (e.g. counts, indices) without requiring a per-key customParser for
     * the common case
     *
     * @tparam T
     */
    template <std::unsigned_integral T>
    requires(!std::same_as<T, bool>)
    struct Converter<T> : public ConverterBase<T>
    {
        using ConverterBase<T>::ConverterBase;

        [[nodiscard]]
        static std::optional<T> tryParse(std::string_view raw);

        [[nodiscard]]
        static std::string describeDomain(const std::vector<T> &notAllowed);
    };

    /**
     * @brief Converter specialization for enums generated by MSTD_ENUM /
     * MSTD_ENUM_BITFLAG
     *
     * @details these enums already carry their own name<->value table via
     * mstd::enum_meta_t<T> -- no separately maintained map is needed here.
     * Per-key aliases or spellings the generated from_string can't express
     * go through InputKey's customParser instead.
     *
     * @tparam T
     */
    template <mstd::has_enum_meta T>
    struct Converter<T> : public ConverterBase<T>
    {
        using ConverterBase<T>::ConverterBase;

        [[nodiscard]]
        static std::optional<T> tryParse(std::string_view raw);

        [[nodiscard]]
        static std::string describeDomain(const std::vector<T> &notAllowed);
    };

    /**
     * @brief Converter specialization for File
     *
     */
    template <>
    struct Converter<mstd::File> : public ConverterBase<mstd::File>
    {
        using ConverterBase<mstd::File>::ConverterBase;

        [[nodiscard]]
        static std::optional<mstd::File> tryParse(std::string_view raw);

        [[nodiscard]]
        static std::string describeDomain(
            const std::vector<mstd::File> &notAllowed
        );
    };

    /**
     * @brief Converter specialization for std::string
     *
     */
    template <>
    struct Converter<std::string> : public ConverterBase<std::string>
    {
        using ConverterBase<std::string>::ConverterBase;

        [[nodiscard]]
        static std::optional<std::string> tryParse(std::string_view raw);
    };

    /**
     * @brief Converter specialization for std::unordered_map<std::string,
     * double>
     *
     */
    template <>
    struct Converter<std::unordered_map<std::string, double>>
        : public ConverterBase<std::unordered_map<std::string, double>>
    {
        using ConverterBase<
            std::unordered_map<std::string, double>>::ConverterBase;

        [[nodiscard]]
        static std::optional<std::unordered_map<std::string, double>> tryParse(
            std::string_view raw
        );

        [[nodiscard]]
        static std::string describeDomain(
            const std::vector<std::unordered_map<std::string, double>>
                &notAllowed
        );
    };

    /**
     * @brief Tag type for selections
     *
     */
    struct SelectionTag
    {
        std::vector<int> indices;
    };

    enum class SelectionError : std::uint8_t
    {
        None,
        NeedsPython,
        InvalidStartIndex,
        OutOfRangeStartIndex,
        InvalidEndIndex,
        OutOfRangeEndIndex,
        InvalidAtomIndex,
        OutOfRangeAtomIndex,
        EmptySelection
    };

    /**
     * @brief Converter specialization for SelectionTag
     *
     */
    template <>
    struct Converter<SelectionTag> : public ConverterBase<SelectionTag>
    {
        using ConverterBase<SelectionTag>::ConverterBase;
        friend class ::TestInputFileReader;

       private:
        SelectionError _selectionError = SelectionError::None;

       public:
        [[nodiscard]]
        std::optional<SelectionTag> tryParse(std::string_view raw);

        [[nodiscard]]
        std::string describeDomain(const std::vector<SelectionTag> &notAllowed);

       private:
        [[nodiscard]]
        std::optional<std::vector<int>> _parseSelectionNoPython(
            const std::string &selection
        );
    };

}   // namespace input

#ifndef _INPUT_CONVERTER_TPP_
#include "inputConverter.tpp"
#endif

#endif   // _INPUT_CONVERTER_HPP_
