name: BUILD

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.github/workflows/ci_build.yml'
      - '.cmake/**'
      - 'apps/**'
      - 'include/**'
      - 'src/**'
      - 'integration_tests/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        build: [Release, Debug]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: install gcc13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
        shell: bash

      - name: setup python ubuntu
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: install python dependencies
        run: |
          python -m pip install numpy
        shell: bash

      - name: install coverage
        if : ${{ matrix.os == 'ubuntu-24.04' && matrix.build == 'Debug' }}
        run: |
          python -m pip install coverage
          python -m pip install gcovr
        shell: bash

      - name: Build and Test Project
        if : ${{ matrix.os != 'ubuntu-24.04' || (matrix.os == 'ubuntu-24.04' && matrix.build != 'Debug') }}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build }} ..
          make -j2
          make test
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Build and Test Project with coverage
        if : ${{ matrix.os == 'ubuntu-24.04' && matrix.build == 'Debug' }}
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_WITH_GCOVR=ON ..
          make -j
          make coverage_xml
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Upload coverage to Codecov
        if : ${{ matrix.os == 'ubuntu-24.04' && matrix.build == 'Debug' }}
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true # optional (default = false)
          gcov: true
          gcov_executable: gcov-13
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Install Integration Test Dependencies
        if: ${{ matrix.build == 'Release' }}
        run: |
          pip install pytest
          pip install pqanalysis

      - name: Integration Tests
        if: ${{ matrix.build == 'Release' }}
        run: |
          pytest integration_tests

