name: RELEASE BUILD

on:
  pull_request:
    branches:
      - '*'
    paths:
      - '.cmake/**'
      - 'apps/**'
      - 'include/**'
      - 'src/**'
      - 'integration_tests/**'
      - 'tests/**'
      - 'CMakeLists.txt'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: install gcc13
        run: |
          sudo apt update
          sudo apt install gcc-13 g++-13
        shell: bash

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: install python dependencies
        run: |
          python -m pip install numpy
        shell: bash

      - name: Build and Test Project
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j20
          make test
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Install Integration Test Dependencies
        if: ${{ matrix.os != 'ubuntu-24.04-arm' }}
        run: |
          pip install pytest
          pip install pytest-cov
          pip install pqanalysis
          pip install setuptools --upgrade
          conda install conda-forge::gsl
          conda install conda-forge::dftbplus

      - name: Integration Tests
        if: ${{ matrix.os != 'ubuntu-24.04-arm' }}
        run: |
          pytest integration_tests
