name: PR Target Branch Update Check

on:
  pull_request:
    branches:
      - main
      - dev
jobs:
  check-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR source branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Fetch target branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}

      - name: Compare commits
        run: |
          # Get the latest commit hashes
          target_commit_hash=$(git rev-parse origin/${{ github.event.pull_request.base.ref }})

          # Check if the target commit is in the history of the source branch
          if git merge-base --is-ancestor $target_commit_hash HEAD; then
            echo "The target branch has new commits since the PR was created."
            exit 1
          else
            echo "No new commits on the target branch since the PR was created."
          fi
